INSERT INTO users (name, age) VALUES ("Shawn", 30);
INSERT INTO users (name, age) VALUES ("Jessica", 31);
INSERT INTO users (name, age) VALUES ("Super Man", 80);
INSERT INTO users (name, age) VALUES ("Steve", 35);
INSERT INTO users (name, age) VALUES ("Guy", 10);
INSERT INTO users (name, age) VALUES ("A Zebra", 6);
INSERT INTO users (name, age) VALUES ("Morgan Freeman", 80);
INSERT INTO users (name, age) VALUES ("Bob", 45);
INSERT INTO users (name, age) VALUES ("Jessica2", 31);
INSERT INTO users (name, age) VALUES ("Maru", 3);
INSERT INTO users (name, age) VALUES ("Hana", 1);
INSERT INTO users (name, age) VALUES ("Lil' Bub", 2);
INSERT INTO users (name, age) VALUES ("Dylan", 27);
INSERT INTO users (name, age) VALUES ("Suzie", 34);
INSERT INTO users (name, age) VALUES ("Josephine", 7);
INSERT INTO users (name, age) VALUES ("Daniel", 51);
INSERT INTO users (name, age) VALUES ("Christopher", 18);
INSERT INTO users (name, age) VALUES ("Jamie", 23);
INSERT INTO users (name, age) VALUES ("Simon", 11);
INSERT INTO users (name, age) VALUES ("Noah", 70);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Fireball Island", "Boardgame", 1000000, 04222018, 05222018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Dinosaur Island", "Boardgame", 500000, 03142018, 04222018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Cheese Gun", "Food", 25000, 01012017, 01012018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Special Sauce", "Food",10000, 11091988, 12091988);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Cheese 3d Printer", "Tech", 1000000000, 05012018, 05022018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Secret Project 1", "Tech", 20, 04041994, 04251994);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Secret Project Cheese", "Food", 25, 04251994, 05171994);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Secret Project Boardgame", "Boardgame", 30, 05181994, 06081994);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Second to Last Project", "Food", 1000, 05051995, 06061996);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) Values ("Super Secret Last Project", "Tech", 5, 04292018, 04302018);

INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (111, 20, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (99, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (456, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (222, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12345, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (54321, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9876, 9, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34, 10, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 11, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (756, 12, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (98, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6324, 14, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90000, 15, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (73924, 16, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (87, 17, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (243, 18, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8934, 19, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (978, 11, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (789, 12, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (23, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (434, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 4, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 19, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 4, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 16, 7);
